{
  assertUnreachable("try { var x = 0 } catch (e) { }");
  assertUnreachable("try { } catch (e) { throw e; }");
}
