{
  assertUnreachable("try { var x = 0 } catch (e) { }");
}
