{
  assertNoWarning("function f() { try { var x = 2; } catch (x) {} }");
}
