{
  try {
    testSame("x-- + 7;");
    fail("Should raise an Exception");
  }
 catch (  RuntimeException e) {
  }
}
